# Generated by Django 4.0.6 on 2022-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=45)),
                ('campaign_description', models.CharField(blank=True, max_length=45, null=True)),
                ('campaign_start_date', models.DateField()),
                ('campaign_finish_date', models.DateField()),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('category_description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_logo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=45)),
                ('condition_description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionList',
            fields=[
                ('condition_list_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'condition_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('donation_name', models.CharField(max_length=45)),
                ('donation_description', models.CharField(blank=True, max_length=45, null=True)),
                ('donation_photo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'donation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonationDetail',
            fields=[
                ('donation_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_expiration_state', models.CharField(max_length=45)),
                ('detail_expiration_date', models.DateField(blank=True, null=True)),
                ('detail_amount', models.SmallIntegerField()),
                ('detail_observation', models.CharField(blank=True, max_length=300, null=True)),
                ('detail_solidarity_points', models.IntegerField()),
                ('detail_register_date', models.DateField()),
            ],
            options={
                'db_table': 'donation_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('location_latitude', models.CharField(max_length=45)),
                ('location_longitude', models.CharField(max_length=45)),
                ('location_reference', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=45, null=True)),
                ('person_document', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('person_address', models.CharField(blank=True, max_length=45, null=True)),
                ('person_photo', models.CharField(blank=True, max_length=45, null=True)),
                ('person_phone', models.CharField(blank=True, max_length=9, null=True, unique=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_date', models.DateField(blank=True, null=True)),
                ('transport_type', models.CharField(db_column='transport\x1f_type', max_length=1)),
            ],
            options={
                'db_table': 'transport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=45)),
                ('user_password', models.CharField(max_length=45)),
                ('user_state', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=45)),
                ('user_type_description', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type_state', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'user_type',
                'managed': False,
            },
        ),
    ]
